# Generated by Django 5.2.6 on 2025-10-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='about_us',
            field=models.TextField(blank=True, help_text='Main About Us/Intro text for the About page.'),
        ),
    ]
