# Generated by Django 5.2.6 on 2025-10-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutpage_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='mission_text',
            field=models.TextField(blank=True, help_text='Mission statement for the About page.'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_text',
            field=models.TextField(blank=True, help_text='Values statement for the About page.'),
        ),
    ]
